#!/usr/bin/env python
"""Generate a static zsh completion for ``rsmanage``.

Click ships a dynamic completion (``_RSMANAGE_COMPLETE=zsh_source rsmanage``),
but it is a poor fit here on two counts: it shells out to Python on every TAB,
which costs about half a second, and its generated script bails out unless
``rsmanage`` is on PATH -- which it is not when the venv is inactive and the
command is reached through ``uv run``.

So we introspect the same click tree once, ahead of time, and emit a plain zsh
function. Completion is then instant and works regardless of PATH. The cost is
that the output is a snapshot: re-run this whenever rsmanage's commands or
options change.

    uv run python development/completions/generate.py

Writes ``development/completions/_rsmanage``; pass a path to write elsewhere,
or ``-`` for stdout.
"""

import sys
from pathlib import Path

import asyncclick as click

from rsptx.rsmanage.core import cli

HEADER = """#compdef rsmanage
# Generated by development/completions/generate.py -- do not edit by hand.
# Re-run that script after changing rsmanage's commands or options.
"""


def esc_desc(text):
    """Escape a description for use inside a zsh ``[...]`` spec."""
    if not text:
        return ""
    # Collapse whitespace: click help strings are often wrapped across lines.
    text = " ".join(text.split())
    for ch in ("\\", "[", "]", ":"):
        text = text.replace(ch, "\\" + ch)
    return text.replace("'", "'\\''")


def esc_tag(text):
    """Escape a description for use in a ``'name:description'`` array entry."""
    if not text:
        return ""
    text = " ".join(text.split())
    text = text.replace("\\", "\\\\").replace(":", "\\:")
    return text.replace("'", "'\\''")


def tag(name, cmd):
    """A ``name:description`` entry, or a bare name when there is no docstring.

    Emitting a trailing colon for an undocumented command makes zsh render a
    dangling ``--`` with nothing after it.
    """
    desc = esc_tag(short_help(cmd))
    return f"{name}:{desc}" if desc else name


def short_help(cmd):
    return cmd.get_short_help_str(limit=60) or ""


def params_of(cmd):
    """All params for a command, including the ``--help`` click adds implicitly.

    ``cmd.params`` omits it; ``get_params`` is what click itself uses to build
    the help page, so it is the honest list.
    """
    return cmd.get_params(click.Context(cmd))


def option_specs(cmd):
    """Yield zsh ``_arguments`` specs for one command's options."""
    specs = []
    for param in params_of(cmd):
        if not isinstance(param, click.Option):
            continue
        desc = esc_desc(param.help)
        # A flag takes no value; everything else needs an argument slot. Choice
        # types get their values completed, paths get file completion, and
        # anything else is left open.
        if param.is_flag:
            action = ""
        elif isinstance(param.type, click.Choice):
            values = " ".join(str(c) for c in param.type.choices)
            action = f":{param.name}:({values})"
        elif isinstance(param.type, (click.Path, click.File)):
            action = f":{param.name}:_files"
        else:
            action = f":{param.name}: "

        for opt in param.opts + param.secondary_opts:
            specs.append(f"'{opt}[{desc}]{action}'")
    return specs


def argument_specs(cmd):
    """Yield zsh ``_arguments`` specs for one command's positional arguments."""
    specs = []
    position = 1
    for param in params_of(cmd):
        if not isinstance(param, click.Argument):
            continue
        name = param.name
        if param.nargs == -1:
            specs.append(f"'*:{name}: '")
            break
        specs.append(f"'{position}:{name}: '")
        position += 1
    return specs


def render_subgroup(name, group):
    """Render a nested group (e.g. ``rsmanage library show``) one level deep.

    Without this the subcommands of a group complete as nothing at all, which
    reads as "this command takes no arguments" rather than "look one level in".
    """
    out = [
        f"                    local -a {name}_cmds",
        f"                    {name}_cmds=(",
    ]
    for sub_name, sub in sorted(group.commands.items()):
        if getattr(sub, "hidden", False):
            continue
        out.append(f"                        '{tag(sub_name, sub)}'")
    out.append("                    )")
    out.append("                    _arguments -C \\")
    out.append("                        '1: :->subcommand' \\")
    out.append("                        '*:: :->subargs'")
    out.append("                    case $state in")
    out.append("                        subcommand)")
    out.append(
        f"                            _describe -t commands '{name} command' {name}_cmds"
    )
    out.append("                            ;;")
    out.append("                        subargs)")
    out.append("                            case $words[1] in")
    for sub_name, sub in sorted(group.commands.items()):
        if getattr(sub, "hidden", False):
            continue
        specs = option_specs(sub) + argument_specs(sub)
        out.append(f"                                {sub_name})")
        if specs:
            out.append("                                    _arguments \\")
            for spec in specs[:-1]:
                out.append(f"                                        {spec} \\")
            out.append(f"                                        {specs[-1]}")
        else:
            out.append("                                    _message 'no options'")
        out.append("                                    ;;")
    out.append("                            esac")
    out.append("                            ;;")
    out.append("                    esac")
    return out


def render():
    out = [HEADER, "", "_rsmanage() {", "    local -a commands", "    local state"]

    out.append("")
    out.append("    commands=(")
    for name, cmd in sorted(cli.commands.items()):
        if getattr(cmd, "hidden", False):
            continue
        out.append(f"        '{tag(name, cmd)}'")
    out.append("    )")

    # Options on the top-level group, then hand off to the subcommand.
    out.append("")
    out.append("    _arguments -C \\")
    for spec in option_specs(cli):
        out.append(f"        {spec} \\")
    out.append("        '1: :->command' \\")
    out.append("        '*:: :->args'")

    out.append("")
    out.append("    case $state in")
    out.append("        command)")
    out.append("            _describe -t commands 'rsmanage command' commands")
    out.append("            ;;")
    out.append("        args)")
    out.append("            case $words[1] in")

    for name, cmd in sorted(cli.commands.items()):
        if getattr(cmd, "hidden", False):
            continue
        out.append(f"                {name})")
        if isinstance(cmd, click.Group):
            out.extend(render_subgroup(name, cmd))
        else:
            specs = option_specs(cmd) + argument_specs(cmd)
            if specs:
                out.append("                    _arguments \\")
                for spec in specs[:-1]:
                    out.append(f"                        {spec} \\")
                out.append(f"                        {specs[-1]}")
            else:
                out.append("                    _message 'no options'")
        out.append("                    ;;")

    out.append("            esac")
    out.append("            ;;")
    out.append("    esac")
    out.append("}")
    out.append("")
    # Work both ways: autoloaded from fpath (zsh calls the function itself, and
    # funcstack[1] is our name), or sourced from .zshrc (register it instead --
    # calling _arguments outside a completion context is an error).
    out.append('if [ "$funcstack[1]" = "_rsmanage" ]; then')
    out.append('    _rsmanage "$@"')
    out.append("else")
    out.append("    compdef _rsmanage rsmanage")
    out.append("fi")
    out.append("")
    return "\n".join(out)


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else None
    text = render()
    if target == "-":
        sys.stdout.write(text)
        return
    path = Path(target) if target else Path(__file__).parent / "_rsmanage"
    path.write_text(text)
    count = len([c for c in cli.commands.values() if not getattr(c, "hidden", False)])
    print(f"Wrote {path} ({count} commands)")


if __name__ == "__main__":
    main()
