version: 2

build:
    os: "ubuntu-24.04"
    tools:
        python: "3.13"
    jobs:
        post_create_environment:
            # Install poetry
            # https://python-poetry.org/docs/#installing-manually
            - pip install poetry
            # Tell poetry to not use a virtual environment
            - poetry config virtualenvs.create false
        post_install:
            # Install dependencies with 'docs' dependency group
            # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
            - poetry self add poetry-polylith-plugin
            - poetry self add poetry-multiproject-plugin
            - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-groups
            # RUNESTONE_PATH is defined in the readthedocs control panel

sphinx:
    configuration: docs/source/conf.py
