version: "3.8"

services:
    author:
        build:
            context: ./projects/author_server
        image: registry.digitalocean.com/runestone-registry/rs-author
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 8114:8114
        command: uvicorn rsptx.author_server_api.main:app --host 0.0.0.0 --port 8114
        volumes:
            - ${BOOK_PATH}:/books
            - $HOME/downloads:/usr/src/app/downloads
        environment:
            - SERVER_CONFIG=${SERVER_CONFIG}
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - DEV_DBURL=${DC_DEV_DBURL:-$DEV_DBURL}
            - DBURL=${DC_DBURL:-$DBURL}
            - RUNESTONE_PATH=/usr/src/app
            - JWT_SECRET=${JWT_SECRET}
        depends_on:
            - redis

    worker:
        build:
            context: ./projects/author_server
        image: registry.digitalocean.com/runestone-registry/rs-worker
        extra_hosts:
            - host.docker.internal:host-gateway
        command: celery -A rsptx.author_server_api.worker.celery worker
        volumes:
            - ${BOOK_PATH}:/books
            - ${SSH_AUTH_SOCK:-/tmp}:/ssh-agent # forward host ssh agent
            - $HOME/downloads:/usr/src/app/downloads
        environment:
            - SERVER_CONFIG=${SERVER_CONFIG}
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - RUNESTONE_PATH=/usr/src/app
            - DEV_DBURL=${DC_DEV_DBURL:-$DEV_DBURL}
            - DBURL=${DC_DBURL:-$DBURL}
            - WEB2PY_CONFIG=${SERVER_CONFIG}
            - JWT_SECRET=${JWT_SECRET}
            - SSH_AUTH_SOCK=/ssh-agent
            - NUM_SERVERS=${NUM_SERVERS:-1}
        depends_on:
            - author
            - redis

    nginx:
        depends_on:
            - author
        links:
            - author
