blank_issues_enabled: false
contact_links:
    - name: Runestone Community Support
      url: https://blog.runestone.academy/pages/support.html
      about: Our slack channel is the best place to get immediate support for questions
    - name: Frequently Asked Questions
      url: https://guide.runestone.academy
      about: Please Check here before asking a question or creating an issue
