"""add_invoice_amount

Revision ID: 086c3f46d8af
Revises: 29cd2a46600d
Create Date: 2024-08-21 14:33:17.250181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086c3f46d8af'
down_revision: Union[str, None] = '29cd2a46600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_request', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_request', 'amount')
    # ### end Alembic commands ###
