"""add last_deploy to library

Revision ID: 143b0d688a8f
Revises: b7f3c1a9d2e4
Create Date: 2026-07-12 06:39:08.739296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143b0d688a8f'
down_revision: Union[str, None] = 'b7f3c1a9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('last_deploy', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'last_deploy')
    # ### end Alembic commands ###
