"""owner_and_editdist

Revision ID: 29cd2a46600d
Revises: 526d79dc9a8f
Create Date: 2024-08-21 10:42:34.646890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cd2a46600d'
down_revision: Union[str, None] = '526d79dc9a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('edit_distance', sa.Integer(), nullable=True))
    op.add_column('code', sa.Column('cps', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('owner', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'owner')
    op.drop_column('code', 'cps')
    op.drop_column('code', 'edit_distance')
    # ### end Alembic commands ###
