"""lti1p3 tables

Revision ID: 2b77aa7142f6
Revises: 4b544994f3da
Create Date: 2025-03-02 08:59:20.562237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b77aa7142f6"
down_revision: Union[str, None] = "4b544994f3da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lti1p3_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=True),
        sa.Column("client_id", sa.String(length=512), nullable=True),
        sa.Column("auth_login_url", sa.String(length=512), nullable=True),
        sa.Column("auth_token_url", sa.String(length=512), nullable=True),
        sa.Column("key_set_url", sa.String(length=512), nullable=True),
        sa.Column("token_audience", sa.String(length=512), nullable=True),
        sa.Column("product_family_code", sa.String(length=512), nullable=True),
        sa.Column("version", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lti1p3_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rs_course_id", sa.Integer(), nullable=False),
        sa.Column("lti1p3_config_id", sa.Integer(), nullable=False),
        sa.Column("lti1p3_course_id", sa.String(length=512), nullable=False),
        sa.Column("course_name", sa.String(length=512), nullable=True),
        sa.Column("deployment_id", sa.String(length=512), nullable=False),
        sa.Column("lineitems_url", sa.String(length=512), nullable=True),
        sa.Column("name_service_url", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["lti1p3_config_id"], ["lti1p3_configs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rs_course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lti1p3_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rs_assignment_id", sa.Integer(), nullable=False),
        sa.Column("lti_lineitem_id", sa.String(length=512), nullable=False),
        sa.Column("lti1p3_course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lti1p3_course_id"], ["lti1p3_courses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rs_assignment_id"], ["assignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lti1p3_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rs_user_id", sa.Integer(), nullable=False),
        sa.Column("lti1p3_course_id", sa.Integer(), nullable=False),
        sa.Column("lti_user_id", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["lti1p3_course_id"], ["lti1p3_courses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rs_user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lti1p3_users")
    op.drop_table("lti1p3_assignments")
    op.drop_table("lti1p3_courses")
    op.drop_table("lti1p3_configs")
    # ### end Alembic commands ###
