"""add allowLink column

Revision ID: 2db61c1550a2
Revises: 8f857bdfef19
Create Date: 2025-10-16 12:47:26.956560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import Web2PyBoolean

# revision identifiers, used by Alembic.
revision: str = '2db61c1550a2'
down_revision: Union[str, None] = '8f857bdfef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline_exceptions', sa.Column('allowLink', Web2PyBoolean(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadline_exceptions', 'allowLink')
    # ### end Alembic commands ###
