"""add apitoken table

Revision ID: 4b544994f3da
Revises: 8559d59ae185
Create Date: 2025-05-28 09:56:54.177659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "4b544994f3da"
down_revision: Union[str, None] = "8559d59ae185"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("token", EncryptedString(length=1024), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
