"""add kind

Revision ID: 526d79dc9a8f
Revises: 7aaca24437eb
Create Date: 2024-02-21 09:57:03.711598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526d79dc9a8f'
down_revision: Union[str, None] = '7aaca24437eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('kind', sa.String(length=128), nullable=True))
    op.alter_column('question_grades', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('useinfo_timestamp_idx', table_name='useinfo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('useinfo_timestamp_idx', 'useinfo', ['timestamp'], unique=False)
    op.alter_column('question_grades', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('assignments', 'kind')
    # ### end Alembic commands ###
