"""add_US_state

Revision ID: 65d7ca534d18
Revises: 5337b0616e8c
Create Date: 2024-09-23 16:30:18.446702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d7ca534d18'
down_revision: Union[str, None] = '5337b0616e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('state', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'state')
    # ### end Alembic commands ###
