"""add_library_columns

Revision ID: 72b94339bbbb
Revises: 65d7ca534d18
Create Date: 2024-10-01 14:24:16.282589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b94339bbbb'
down_revision: Union[str, None] = '65d7ca534d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('source_path', sa.String(length=512), nullable=True))
    op.add_column('library', sa.Column('target', sa.String(length=128), nullable=True))
    op.add_column('library', sa.Column('default_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'default_language')
    op.drop_column('library', 'target')
    op.drop_column('library', 'source_path')
    # ### end Alembic commands ###
