"""create baseline

Revision ID: 7aaca24437eb
Revises:
Create Date: 2024-02-12 18:08:18.272500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7aaca24437eb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table("auth_cas")
        op.drop_table("auth_permission")
        op.drop_table("user_biography")
    except Exception as e:
        print("Tables already dropped")
    try:
        op.create_unique_constraint(
            None, "editor_basecourse", ["editor", "base_course"]
        )
    except Exception as e:
        print("Constraint already created")

    op.add_column("questions", sa.Column("question_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
