"""add matching answers

Revision ID: 8559d59ae185
Revises: 37b73c74eebe
Create Date: 2025-04-25 16:13:52.126136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import Web2PyBoolean

# revision identifiers, used by Alembic.
revision: str = "8559d59ae185"
down_revision: Union[str, None] = "37b73c74eebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matching_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("div_id", sa.String(length=512), nullable=False),
        sa.Column("sid", sa.String(length=512), nullable=False),
        sa.Column("correct", Web2PyBoolean(length=1), nullable=False),
        sa.Column("percent", sa.Float(), nullable=True),
        sa.Column("answer", sa.JSON(), nullable=False),
        sa.Column("course_name", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_name"],
            ["courses.course_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_div_sid_course_match",
        "matching_answers",
        ["sid", "div_id", "course_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matching_answers_course_name"),
        "matching_answers",
        ["course_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matching_answers_div_id"), "matching_answers", ["div_id"], unique=False
    )
    op.create_index(
        op.f("ix_matching_answers_sid"), "matching_answers", ["sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matching_answers_sid"), table_name="matching_answers")
    op.drop_index(op.f("ix_matching_answers_div_id"), table_name="matching_answers")
    op.drop_index(
        op.f("ix_matching_answers_course_name"), table_name="matching_answers"
    )
    op.drop_index("idx_div_sid_course_match", table_name="matching_answers")
    op.drop_table("matching_answers")
    # ### end Alembic commands ###
