"""add telemetry tables

Revision ID: 865a6dbf6c09
Revises: fada6d479f83
Create Date: 2026-06-11 14:32:56.907451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865a6dbf6c09'
down_revision: Union[str, None] = 'fada6d479f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('base_courses', sa.Text(), nullable=True),
    sa.Column('course_count_bucket', sa.String(length=32), nullable=True),
    sa.Column('student_count_bucket', sa.String(length=32), nullable=True),
    sa.Column('institution', sa.String(length=512), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_instance_id'), 'installation', ['instance_id'], unique=True)
    op.create_table('telemetry_state',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('last_sent', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_state')
    op.drop_index(op.f('ix_installation_instance_id'), table_name='installation')
    op.drop_table('installation')
    # ### end Alembic commands ###
