"""add repo_path to library model

Revision ID: 8e9108d94e08
Revises: b28d6db94abb
Create Date: 2024-11-26 14:44:12.092941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e9108d94e08"
down_revision: Union[str, None] = "b28d6db94abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "library", sa.Column("repo_path", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library", "repo_path")
    # ### end Alembic commands ###
