"""add timezone column

Revision ID: 8f857bdfef19
Revises: b209fe8b2841
Create Date: 2025-10-07 08:25:49.368141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f857bdfef19'
down_revision: Union[str, None] = 'b209fe8b2841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('timezone', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'timezone')
    # ### end Alembic commands ###
