"""add build hooks to library

Revision ID: a91c47d2e8b3
Revises: 143b0d688a8f
Create Date: 2026-07-12 09:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91c47d2e8b3'
down_revision: Union[str, None] = '143b0d688a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('prebuild_hook', sa.String(length=512), nullable=True))
    op.add_column('library', sa.Column('postbuild_hook', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'postbuild_hook')
    op.drop_column('library', 'prebuild_hook')
    # ### end Alembic commands ###
