"""add domain_name column to courses

Revision ID: b209fe8b2841
Revises: f5db38d9355f
Create Date: 2025-05-30 11:44:29.274114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b209fe8b2841'
down_revision: Union[str, None] = 'f5db38d9355f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('domain_name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'domain_name')
    # ### end Alembic commands ###
