"""add_deadline_exceptions

Revision ID: b28d6db94abb
Revises: 72b94339bbbb
Create Date: 2024-10-17 15:49:10.018516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import Web2PyBoolean

# revision identifiers, used by Alembic.
revision: str = "b28d6db94abb"
down_revision: Union[str, None] = "72b94339bbbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deadline_exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "course_id", sa.Integer(), sa.ForeignKey("courses.id"), nullable=False
        ),
        sa.Column(
            "assignment_id", sa.Integer(), sa.ForeignKey("assignments.id"), nullable=True
        ),
        sa.Column(
            "sid", sa.String(), sa.ForeignKey("auth_user.username"), nullable=False
        ),
        sa.Column("visible", Web2PyBoolean(length=1), nullable=True),
        sa.Column("duedate", sa.Integer(), nullable=True),
        sa.Column("time_limit", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deadline_exceptions_assignment_id"),
        "deadline_exceptions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_exceptions_course_id"),
        "deadline_exceptions",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_exceptions_sid"), "deadline_exceptions", ["sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deadline_exceptions_sid"), table_name="deadline_exceptions")
    op.drop_index(
        op.f("ix_deadline_exceptions_course_id"), table_name="deadline_exceptions"
    )
    op.drop_index(
        op.f("ix_deadline_exceptions_assignment_id"), table_name="deadline_exceptions"
    )
    op.drop_table("deadline_exceptions")
    # ### end Alembic commands ###
