"""add domain_approvals

Revision ID: f5db38d9355f
Revises: 2b77aa7142f6
Create Date: 2025-05-30 11:10:40.978083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import Web2PyBoolean


# revision identifiers, used by Alembic.
revision: str = 'f5db38d9355f'
down_revision: Union[str, None] = '2b77aa7142f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_approvals',
    sa.Column('domain_name', sa.String(length=512), nullable=False),
    sa.Column('lti1p3', Web2PyBoolean(length=1), nullable=True),
    sa.PrimaryKeyConstraint('domain_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_approvals')
    # ### end Alembic commands ###
