"""add_splice_answers

Revision ID: fabe9802c36a
Revises: 8e9108d94e08
Create Date: 2024-12-08 16:14:46.391271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from rsptx.db.models import Web2PyBoolean


# revision identifiers, used by Alembic.
revision: str = "fabe9802c36a"
down_revision: Union[str, None] = "8e9108d94e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "splice_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("div_id", sa.String(length=512), nullable=False),
        sa.Column("sid", sa.String(length=512), nullable=False),
        sa.Column("correct", Web2PyBoolean(length=1), nullable=False),
        sa.Column("percent", sa.Float(), nullable=True),
        sa.Column("answer", sa.JSON(), nullable=False),
        sa.Column("course_name", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_name"],
            ["courses.course_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_div_sid_course_sp",
        "splice_answers",
        ["sid", "div_id", "course_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_splice_answers_course_name"),
        "splice_answers",
        ["course_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_splice_answers_div_id"), "splice_answers", ["div_id"], unique=False
    )
    op.create_index(
        op.f("ix_splice_answers_sid"), "splice_answers", ["sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_splice_answers_sid"), table_name="splice_answers")
    op.drop_index(op.f("ix_splice_answers_div_id"), table_name="splice_answers")
    op.drop_index(op.f("ix_splice_answers_course_name"), table_name="splice_answers")
    op.drop_index("idx_div_sid_course_sp", table_name="splice_answers")
    op.drop_table("splice_answers")
    # ### end Alembic commands ###
