"""empty message

Revision ID: fada6d479f83
Revises: c1d2e3f4a5b6
Create Date: 2026-05-28 06:25:44.446617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fada6d479f83'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_questions', sa.Column('async_mode', sa.String(length=20), server_default='standard', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_questions', 'async_mode')
    # ### end Alembic commands ###
